-- =============================================================================
-- Migration 00005: Import reference data from Cloudflare D1
--
-- Tables imported:
--   - dim_exercices (59 rows) + add exercise_subtype column
--   - dim_seance (10 rows)
--   - dim_seance_deroule (40 rows)
--
-- Groups are handled by 00004_seed_groups.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Add missing exercise_subtype column (exists in D1 but not in schema)
-- ---------------------------------------------------------------------------
ALTER TABLE dim_exercices ADD COLUMN IF NOT EXISTS exercise_subtype TEXT;

-- ---------------------------------------------------------------------------
-- 1b. Fix numero_seance type: D1 stores TEXT ('S1','S2'...) in INTEGER column
--     (SQLite is dynamically typed; PostgreSQL is not)
-- ---------------------------------------------------------------------------
DROP INDEX IF EXISTS idx_dim_seance_numero;
ALTER TABLE dim_seance ALTER COLUMN numero_seance TYPE TEXT USING numero_seance::TEXT;
ALTER TABLE dim_seance_deroule ALTER COLUMN numero_seance TYPE TEXT USING numero_seance::TEXT;
CREATE INDEX idx_dim_seance_numero ON dim_seance (numero_seance);

-- ---------------------------------------------------------------------------
-- 2. Import dim_exercices (59 rows)
-- ---------------------------------------------------------------------------
INSERT INTO dim_exercices (
  id, numero_exercice, nom_exercice, description, illustration_gif, exercise_type,
  nb_series_endurance, nb_reps_endurance, pourcentage_charge_1rm_endurance,
  recup_series_endurance, recup_exercices_endurance,
  nb_series_hypertrophie, nb_reps_hypertrophie, pourcentage_charge_1rm_hypertrophie,
  recup_series_hypertrophie, recup_exercices_hypertrophie,
  nb_series_force, nb_reps_force, pourcentage_charge_1rm_force,
  recup_series_force, recup_exercices_force,
  exercise_subtype
) VALUES
(1, NULL, 'Développé militaire', 'Développé militaire (poussée verticale) : utile pour la robustesse de l''épaule et la stabilité au-dessus de la tête (streamline, entrées de bras). À équilibrer avec beaucoup de tirages et du travail de coiffe/scapula pour limiter les douleurs d''épaule chez les nageurs. Priorité à une exécution contrôlée, cage "rentrée", omoplates stables.', 'https://burnfit.io/wp-content/uploads/2023/11/SEAT_DB_SHD_PRESS.gif', 'strength', 4, 16, 60.0, 120, 300, 3, 8, 75.0, 200, 300, 3, 3, 85.0, 300, 500, 'strength_accessory'),
(2, NULL, 'Développé couché barre', 'Développé couché barre : renforce pectoraux/triceps et améliore la tolérance aux charges en poussée. Pour un nageur, c''est surtout un exercice d''équilibre (antagoniste) : il aide à la robustesse générale, mais doit rester secondaire par rapport aux tirages (dorsaux) et au contrôle scapulaire. Éviter de "fermer" l''épaule : amplitude maîtrisée, omoplates serrées.', 'https://burnfit.io/wp-content/uploads/2023/11/BB_BP.gif', 'strength', 4, 12, 60.0, 150, 300, 4, 8, 75.0, 210, 300, 5, 3, 85.0, 330, 500, 'strength_accessory'),
(3, NULL, 'Romanian DeadLift', 'Romanian Deadlift (RDL) : renforce ischios/fessiers et la charnière hanche, indispensable pour la puissance des jambes (départs/virages) et un bassin stable en ondulation/coulée. Très bon pour prévenir les soucis lombaires si la technique est propre (dos neutre, tension ischios).', 'https://burnfit.io/wp-content/uploads/2023/11/RM_BB_DL.gif', 'strength', 4, 12, 60.0, 150, 300, 4, 8, 75.0, 210, 300, 5, 3, 85.0, 330, 500, 'strength_accessory'),
(4, NULL, 'Incline Dumbbell Row', 'Incline Dumbbell Row (rowing poitrine appuyée) : très "spécifique natation" car il développe la traction horizontale (dorsaux/rhomboïdes) avec peu de fatigue lombaire. Excellent transfert sur la phase de traction en crawl/dos/papillon et sur la posture scapulaire pour encaisser du volume sans douleur.', 'https://burnfit.io/wp-content/uploads/2023/11/INC_DB_ROW.gif', 'strength', 3, 15, 60.0, 120, 240, 4, 10, 75.0, 180, 240, 4, 6, 80.0, 240, 360, 'strength_accessory'),
(5, NULL, 'Tractions prise neutre', 'Tractions prise neutre : développe la force relative et la dépression scapulaire, clés pour une propulsion efficace et une épaule saine (moins de conflit). Très intéressant en sprint et pour la robustesse générale. Variante : amplitude stricte, contrôle des omoplates, progression vers traction lestée.', 'https://www.docteur-fitness.com/wp-content/uploads/2022/10/traction-prise-neutre.gif', 'strength', 4, 10, 0.0, 120, 240, 4, 8, 0.0, 180, 240, 5, 5, 0.0, 240, 360, 'strength_accessory'),
(6, NULL, 'Front Squat', 'Front Squat : renforce quadriceps + gainage + posture, utile pour la poussée au mur (virage) et la rigidité du tronc au départ. Le front squat demande une bonne mobilité cheville/hanche : excellent pour "transférer" la force jambes → tronc sans s''écraser.', 'https://burnfit.io/wp-content/uploads/2023/11/BB_FSQ.gif', 'strength', 4, 12, 60.0, 150, 300, 4, 8, 75.0, 210, 300, 5, 3, 85.0, 330, 500, 'strength_accessory'),
(7, NULL, 'Trap Bar Deadlift', 'Trap Bar Deadlift : gros retour sur investissement pour force/puissance bas du corps, souvent plus accessible techniquement que le deadlift classique. Très pertinent pour départs et virages (impulsion), et pour "convertir" la force en vitesse de poussée. Garder une intention explosive surtout sur les séries courtes.', 'https://burnfit.io/wp-content/uploads/2023/11/TRAP_DL.gif', 'strength', 4, 12, 60.0, 150, 300, 4, 8, 75.0, 210, 300, 5, 3, 85.0, 330, 500, 'power'),
(8, NULL, 'Box Jump', 'Box Jump : plyométrie pour améliorer le taux de développement de force (RFD), directement utile pour départs/virages. Pour les nageurs : qualité > quantité, récup longues, atterrissages silencieux. Arrêter la série dès que la hauteur/vitesse baisse.', 'https://burnfit.io/wp-content/uploads/2023/11/BOX_JUMP.gif', 'strength', 4, 5, 0.0, 120, 300, 5, 4, 0.0, 150, 300, 6, 3, 0.0, 180, 360, 'plyometric'),
(9, NULL, 'Med Ball Slam', 'Med Ball Slam : puissance tronc/épaules et coordination bras-tronc. Intéressant pour le sprint (crawl/papillon) : meilleure transmission de force et explosivité sans charge lourde sur les articulations. Conserver un gainage fort et une intention maximale à chaque rep.', 'https://fitnessprogramer.com/wp-content/uploads/2022/06/Medicine-ball-Overhead-Slam-exercise.gif', 'strength', 4, 8, 0.0, 90, 240, 5, 6, 0.0, 120, 240, 6, 4, 0.0, 150, 300, 'power'),
(10, NULL, 'Corde à sauter', 'Corde à sauter : échauffement "cardio-coordination" et travail de pieds/chevilles utile pour la rigidité au départ/virage. Bon outil d''activation avant musculation ou séance d''eau : monter progressivement en intensité, rester léger sur l''avant-pied.', 'https://burnfit.io/wp-content/uploads/2023/11/JUMP_ROPE.gif', 'strength', 5, 60, 0.0, 60, 180, 6, 45, 0.0, 60, 180, 8, 30, 0.0, 90, 240, 'conditioning'),
(11, NULL, 'Tirage vertical unilatéral supination assis bas', 'Exercice très spécifique nage : la prise supination et la trajectoire basse permettent une forte sollicitation du grand dorsal sur toute l''amplitude. Le travail unilatéral améliore la connexion tronc–bras et la symétrie. Très bon transfert sur la phase de traction en crawl et papillon.', 'https://api.smartworkout.app/asset/image/e18cdc91-2f42-46d3-b25e-95350c260e11', 'strength', 3, 12, 60.0, 120, 240, 4, 10, 75.0, 180, 240, 4, 6, 80.0, 240, 360, 'strength_accessory'),
(12, NULL, 'Straight-Arm Pulldown barre (pattern papillon)', 'Bras tendus, trajectoire proche du mouvement de papillon. Cet exercice apprend à engager le grand dorsal sans plier les bras, avec un fort gainage. Excellent pour améliorer la qualité de prise d''eau et la connexion bras–tronc en papillon et crawl.', 'https://burnfit.io/wp-content/uploads/2023/11/CABLE_ARM_PULL_DOWN.gif', 'strength', 3, 15, 55.0, 90, 240, 4, 12, 65.0, 120, 240, 4, 8, 70.0, 150, 300, 'power'),
(13, NULL, 'Tractions lestées', 'Version force des tractions : développe la force maximale et la force relative, très importantes chez les nageurs sprinteurs. Fort transfert sur la propulsion et la capacité à produire beaucoup de force par coup de bras. Progression : technique stricte, puis ajout de charge progressive.', 'https://www.docteur-fitness.com/wp-content/uploads/2022/02/traction-lestee.gif', 'strength', 4, 8, 60.0, 150, 240, 4, 6, 75.0, 210, 240, 5, 3, 85.0, 330, 500, 'power'),
(14, NULL, 'Dips', 'Travail de poussée sollicitant triceps, pectoraux et ceinture scapulaire. Intéressant pour la robustesse du haut du corps chez le nageur, mais à équilibrer avec beaucoup de tirages (dorsaux/rhomboïdes) pour préserver l''épaule. Garder les épaules basses et le buste gainé.', 'https://burnfit.io/wp-content/uploads/2023/11/DIPS.gif', 'strength', 4, 12, 0.0, 120, 240, 4, 8, 0.0, 180, 240, 5, 5, 0.0, 240, 360, 'strength_accessory'),
(15, NULL, 'L-Sit', 'Gainage actif très exigeant combinant tronc et fléchisseurs de hanche. Excellent pour la rigidité du corps, la coulée, l''ondulation et le maintien d''une ligne hydrodynamique. Variante plus facile : tuck sit. Progression : durée puis jambes tendues.', 'https://liftmanual.com/wp-content/uploads/2023/04/l-sit.gif', 'strength', 4, 20, 0.0, 45, 90, 4, 15, 0.0, 60, 120, 5, 12, 0.0, 75, 150, 'core'),
(16, NULL, 'Tirage vertical prise neutre', 'Alternative guidée aux tractions. Permet de travailler le grand dorsal avec une trajectoire stable et un volume plus élevé. Très utile pour l''hypertrophie spécifique nage et la qualité de la traction, surtout en période de gros volume en bassin. Se concentrer sur la dépression scapulaire avant de tirer.', 'https://www.docteur-fitness.com/wp-content/uploads/2021/08/tirage-vertical-prise-serree.gif', 'strength', 3, 15, 60.0, 120, 240, 4, 10, 75.0, 180, 240, 4, 6, 80.0, 240, 360, 'strength_accessory'),
(17, NULL, 'Bench Pull explosif', 'Variante explosive du bench pull avec intention de vitesse. Développe la capacité à produire de la force rapidement, très utile pour l''accélération du bras en sprint (crawl, dos, papillon). La charge doit permettre une exécution rapide et propre.', 'https://www.docteur-fitness.com/wp-content/uploads/2022/02/rowing-halteres-banc-incline-supination.gif', 'strength', 5, 5, 50.0, 150, 300, 6, 4, 55.0, 180, 300, 8, 3, 60.0, 210, 360, 'power'),
(18, NULL, 'Rowing unilatéral haltère appui banc', 'Travail unilatéral permettant une grande amplitude et une forte sollicitation du grand dorsal. Excellent pour corriger les asymétries et améliorer la connexion tronc–bras, avec un très bon transfert sur la propulsion en crawl et dos.', 'https://burnfit.io/wp-content/uploads/2023/11/OA_DB_ROW.gif', 'strength', 3, 15, 60.0, 120, 240, 4, 10, 75.0, 180, 240, 4, 6, 80.0, 240, 360, 'strength_accessory'),
(19, NULL, 'Pull-over barre', 'Exercice d''extension d''épaule sollicitant fortement le grand dorsal sur une grande amplitude. Utile pour améliorer la fin de traction et la connexion bras–tronc, particulièrement appréciée en crawl et papillon.', 'https://burnfit.io/wp-content/uploads/2023/11/BB_PULLOVER.gif', 'strength', 3, 15, 60.0, 120, 240, 4, 10, 70.0, 150, 240, 4, 8, 75.0, 180, 300, 'strength_accessory'),
(20, NULL, 'Squat Jump chargé léger', 'Exercice de transition force–puissance. Permet de convertir la force des jambes en explosivité, directement transférable sur la poussée au départ et aux virages. La charge reste légère pour préserver la vitesse du saut.', 'https://fitnessprogramer.com/wp-content/uploads/2022/04/Dumbbell-Jump-Squat.gif', 'strength', 4, 5, 20.0, 120, 300, 5, 4, 25.0, 150, 300, 6, 3, 30.0, 180, 360, 'plyometric'),
(21, NULL, 'Broad Jump', 'Saut horizontal visant la projection vers l''avant. Très spécifique du départ plongé en natation, il développe la puissance horizontale et la coordination jambes–tronc.', 'https://liftmanual.com/wp-content/uploads/2023/04/standing-long-jump.gif', 'strength', 4, 5, 0.0, 120, 300, 5, 4, 0.0, 150, 300, 6, 3, 0.0, 180, 360, 'plyometric'),
(22, NULL, 'Hip Thrust explosif', 'Développe l''extension de hanche avec une intention explosive. Très pertinent pour la poussée murale, l''ondulation et la rigidité du bassin chez les nageurs, notamment en papillon et au départ.', 'https://burnfit.io/wp-content/uploads/2023/11/WEI_HIP_THRUST.gif', 'strength', 4, 6, 55.0, 150, 300, 5, 5, 65.0, 180, 300, 6, 3, 75.0, 210, 360, 'power'),
(23, NULL, 'Hanging Leg Raises', 'Gainage dynamique suspendu sollicitant fortement le tronc et les fléchisseurs de hanche. Excellent transfert sur la coulée, l''ondulation et la capacité à maintenir une ligne hydrodynamique sous l''eau.', 'https://burnfit.io/wp-content/uploads/2023/11/HANG_LEG_RAIGE.gif', 'strength', 3, 20, 0.0, 45, 90, 3, 15, 0.0, 60, 120, 4, 10, 0.0, 75, 150, 'core'),
(24, NULL, 'Y-T-W épaules', 'Exercice de prévention renforçant les trapèzes moyens et inférieurs ainsi que la coiffe des rotateurs. Indispensable pour maintenir la santé des épaules face aux volumes élevés de nage.', 'https://burnfit.io/wp-content/uploads/2023/11/Y_RAISE.gif', 'strength', 2, 20, 0.0, 45, 90, 3, 15, 0.0, 60, 120, 3, 10, 0.0, 75, 150, 'prehab'),
(25, NULL, 'Incline Dumbbell Twist Press', 'Incline Dumbbell Twist Press : développé incliné avec rotation contrôlée, intéressant pour renforcer la poussée (pectoraux/épaules/triceps) tout en travaillant le contrôle du tronc et la coordination bras–buste. Pour les nageurs, c''est un bon exercice "d''équilibre" antagoniste : priorité à une trajectoire propre, omoplates stables, rotation fluide sans compenser avec le bas du dos.', 'https://burnfit.io/wp-content/uploads/2023/11/INC_DB_TWIST_PRESS.gif', 'strength', 3, 15, 55.0, 120, 240, 4, 10, 70.0, 150, 240, 4, 6, 75.0, 210, 300, NULL),
(26, NULL, 'Back Squat', 'Back Squat : exercice majeur pour la force des jambes (quadriceps/fessiers) et la capacité à produire de la puissance au départ et aux virages. Chez le nageur, on vise une technique solide (dos neutre, genoux stables) et des séries de qualité pour construire une base de force sans épuiser le système nerveux. Très utile aussi pour la robustesse générale et la tolérance aux charges.', 'https://burnfit.io/wp-content/uploads/2023/11/BB_BSQT.gif', 'strength', 4, 12, 60.0, 150, 300, 4, 8, 75.0, 210, 300, 5, 3, 85.0, 330, 500, NULL),
(27, NULL, 'Jump Squat', 'Jump Squat : saut avec charge légère ou modérée visant la puissance verticale et la vitesse d''extension. Très rentable pour convertir la force en explosivité, utile pour départs et virages. Clés : intention maximale, reps faibles, récup longues, arrêter dès que la hauteur ou la vitesse baisse.', 'https://burnfit.io/wp-content/uploads/2023/11/JUMP_SQT.gif', 'strength', 4, 5, 20.0, 120, 300, 5, 4, 25.0, 150, 300, 6, 3, 30.0, 180, 360, NULL),
(28, NULL, 'Leg Curl', 'Leg Curl : isolation des ischios-jambiers, utile pour équilibrer la chaîne postérieure, prévenir les blessures et renforcer la phase de flexion du genou sans charger le dos. Pour les nageurs, c''est un bon complément aux hinges (RDL/trap bar) pour solidifier ischios et genou, surtout en périodes de volume bassin élevé.', 'https://burnfit.io/wp-content/uploads/2023/11/LEG_CURL.gif', 'strength', 3, 15, 60.0, 90, 240, 4, 10, 70.0, 120, 240, 4, 6, 75.0, 180, 300, NULL),
(29, NULL, 'Leg Press', 'Leg Press : renforce quadriceps/fessiers avec une contrainte technique plus simple que le squat, utile pour développer de la force jambes et de la "réserve" de poussée pour départs/virages. Pour les nageurs, c''est un bon outil quand la fatigue ou la mobilité limite les squats, en gardant une amplitude contrôlée et un bassin stable.', 'https://burnfit.io/wp-content/uploads/2023/11/LEG_PRESS.gif', 'strength', 4, 15, 60.0, 150, 300, 4, 10, 75.0, 210, 300, 5, 5, 85.0, 330, 500, NULL),
(30, NULL, 'Farmer walk', 'Farmer Walk : carry bilatéral lourd qui développe gainage global, prise, trapèzes et stabilité scapulaire. Excellent pour la "rigidité utile" (transmission de force) et la robustesse du tronc, avec un transfert indirect sur coulées/streamline et la tolérance aux charges en haut du corps. Marcher grand, épaules basses, tronc verrouillé.', 'https://burnfit.io/wp-content/uploads/2023/11/FARMER_WALK.gif', 'strength', 4, 30, 60.0, 90, 180, 4, 25, 70.0, 120, 240, 5, 20, 80.0, 150, 300, NULL),
(31, NULL, 'Burpee', 'Burpee : exercice métabolique full body combinant squat, gainage et poussée. Utile comme finisher ou travail de conditionnement général, mais à doser chez les nageurs pour ne pas nuire à la qualité en bassin. Priorité à une exécution propre (gainage, respiration) plutôt qu''à la vitesse "désordonnée".', 'https://burnfit.io/wp-content/uploads/2023/11/BURPEE.gif', 'strength', 4, 12, 0.0, 90, 240, 5, 8, 0.0, 120, 240, 6, 5, 0.0, 150, 300, NULL),
(32, NULL, 'Abdos', 'Abdos : travail général du tronc (flexion/anti-extension/anti-rotation selon la variante) visant la rigidité et le contrôle du bassin. Pour les nageurs, l''objectif principal est de mieux transmettre la force et de maintenir une ligne hydrodynamique (coulées, ondulations, virages). Privilégier la qualité du gainage et la respiration.', 'https://burnfit.io/wp-content/uploads/2023/11/SIT_UP.gif', 'strength', 3, 25, 0.0, 45, 90, 4, 20, 0.0, 60, 120, 4, 15, 0.0, 75, 150, NULL),
(33, NULL, 'Bulgarian Split Squat', 'Bulgarian Split Squat : squat unilatéral très efficace pour force et stabilité hanche-genou-cheville. Excellent pour corriger les asymétries et améliorer la poussée spécifique jambe par jambe, utile pour virages et départs. Garder le buste gainé, genou aligné, amplitude contrôlée (pas de rebond).', 'https://burnfit.io/wp-content/uploads/2023/11/DB_BULSPLIT_SQT.gif', 'strength', 3, 12, 55.0, 120, 240, 4, 8, 70.0, 180, 240, 5, 5, 75.0, 240, 360, NULL),
(34, NULL, 'Step-Up', 'Step-Up : montée sur banc développant force unilatérale et coordination, avec un bon transfert sur la production de force "en appui" et la stabilité du bassin. Très utile chez les nageurs pour limiter les déséquilibres et renforcer jambes/fessiers sans charger lourd la colonne. Monter en contrôlant, redescendre sans s''écraser.', 'https://burnfit.io/wp-content/uploads/2023/11/STEP_UP.gif', 'strength', 3, 12, 55.0, 120, 240, 4, 8, 70.0, 180, 240, 5, 5, 75.0, 240, 360, NULL),
(35, NULL, 'Reverse Lunge', 'Reverse Lunge (fente arrière) : renforce jambes/fessiers avec une contrainte plus douce pour le genou qu''une fente avant, tout en travaillant l''équilibre et la stabilité du tronc. Pour les nageurs, c''est un excellent outil de robustesse et de force unilatérale, utile pour virages/départs et prévention.', 'https://fitnessprogramer.com/wp-content/uploads/2022/08/bodyweight-reverse-lunge.gif', 'strength', 3, 12, 55.0, 120, 240, 4, 8, 70.0, 180, 240, 5, 5, 75.0, 240, 360, NULL),
(36, NULL, 'Single-Leg Romanian DeadLift', 'Single-Leg Romanian Deadlift : hinge unilatéral ciblant ischios/fessiers avec gros travail d''équilibre et de contrôle du bassin. Très intéressant pour la stabilité lombo-pelvienne et la prévention, avec transfert sur poussée/ondulation via une chaîne postérieure solide. Clé : hanches "carrées", dos neutre, amplitude maîtrisée.', 'https://burnfit.io/wp-content/uploads/2023/11/BB_SL_DEAD.gif', 'strength', 3, 12, 55.0, 120, 240, 4, 8, 70.0, 180, 240, 5, 5, 75.0, 240, 360, NULL),
(37, NULL, 'Lateral Lunge', 'Lateral Lunge : fente latérale travaillant adducteurs, fessiers et contrôle frontal. Utile pour la robustesse des hanches et la prévention (notamment chez brasseurs/4N), et pour améliorer la stabilité des appuis. Garder le genou aligné, poids sur le milieu du pied, retour contrôlé.', 'https://burnfit.io/wp-content/uploads/2023/11/DB_LAT_LUNGE.gif', 'strength', 3, 12, 55.0, 120, 240, 4, 8, 70.0, 180, 240, 5, 5, 75.0, 240, 360, NULL),
(38, NULL, 'Nordic Hamstring Curl', 'Nordic Hamstring Curl : renforcement très puissant des ischios en excentrique, excellent pour la prévention et la capacité à produire/absorber de la force. Pour les nageurs, c''est un exercice "haut rendement" pour solidifier la chaîne postérieure sans charge externe lourde, mais à doser car il peut donner des courbatures importantes.', 'https://fitnessprogramer.com/wp-content/uploads/2022/06/Nordic-Hamstring-Curl.gif', 'strength', 3, 6, 0.0, 150, 240, 4, 5, 0.0, 180, 240, 5, 3, 0.0, 240, 360, NULL),
(39, NULL, 'Sliding Leg Curl', 'Sliding Leg Curl : leg curl au sol (serviettes/sliders) qui renforce ischios et gainage en chaîne fermée. Intéressant pour développer la chaîne postérieure avec un coût articulaire faible, et très utile en prévention/robustesse. Contrôler la descente, bassin stable, éviter de cambrer.', NULL, 'strength', 3, 10, 0.0, 120, 240, 4, 8, 0.0, 150, 240, 5, 6, 0.0, 180, 300, NULL),
(40, NULL, 'Back Extension 45°', 'Back Extension 45° : extension de hanche/rachis sur banc à 45°, visant fessiers, ischios et érecteurs du rachis. Très utile pour renforcer la charnière hanche et la tolérance lombaire, important pour encaisser la charge (squat/hinge) et maintenir une posture solide en nage. Priorité : bouger depuis les hanches, dos neutre.', NULL, 'strength', 3, 15, 50.0, 90, 240, 4, 12, 60.0, 120, 240, 4, 8, 70.0, 150, 300, NULL),
(41, NULL, 'Standing Calf Raise', 'Standing Calf Raise : renforce le mollet (gastrocnémien) et la rigidité cheville-pied, essentielle pour la réactivité au départ et la poussée au mur. Chez les nageurs, c''est un exercice simple mais très utile pour améliorer le "ressort" et la capacité à transmettre la force au sol. Monter contrôlé, pause en haut, descendre complet.', NULL, 'strength', 4, 15, 50.0, 60, 180, 4, 12, 65.0, 75, 180, 5, 8, 75.0, 90, 240, NULL),
(42, NULL, 'Seated Soleus Raise', 'Seated Soleus Raise : cible le soléaire (mollet genou fléchi), clé pour la stabilité de cheville et l''endurance des appuis. Très intéressant pour départs/virages (stiffness) et la prévention des douleurs tendon/Achille. Garder une amplitude complète, tempo contrôlé, éviter les rebonds.', NULL, 'strength', 4, 20, 45.0, 60, 180, 4, 15, 60.0, 75, 180, 5, 10, 70.0, 90, 240, NULL),
(43, NULL, 'Pogo Hops', 'Pogo Hops : petits sauts rapides et "élastiques" (faible amplitude) visant la réactivité cheville et le cycle étirement-raccourcissement. Très utile pour améliorer la stiffness et la vitesse d''appui, transférable aux départs/virages. Consignes : posture haute, contacts très courts, arrêter dès que la réactivité baisse.', NULL, 'strength', 3, 20, 0.0, 60, 180, 4, 15, 0.0, 75, 180, 5, 10, 0.0, 90, 240, NULL),
(44, NULL, 'Ankle Isometric Hold', 'Ankle Isometric Hold : maintien isométrique cheville/mollet dans une position de poussée (souvent sur demi-pointe) pour développer la rigidité et la tolérance tendineuse. Très utile pour solidifier l''Achille et améliorer la transmission de force au départ/virage, avec faible fatigue systémique. Tenir "fort mais propre", sans trembler excessivement.', NULL, 'strength', 3, 30, 0.0, 45, 120, 4, 20, 0.0, 60, 150, 5, 12, 0.0, 75, 180, NULL),
(45, NULL, 'Pallof Press', 'Pallof Press : anti-rotation du tronc au câble/élastique, excellent pour stabiliser le bassin et empêcher les compensations. Transfert direct sur la qualité de la ligne (coulée/ondulation) et sur la transmission de force bras-jambes, tout en protégeant le bas du dos. Garder côtes basses, bassin neutre, respiration contrôlée.', 'https://fitnessprogramer.com/wp-content/uploads/2024/05/Cable-Half-Kneeling-Pallof-Press.gif', 'strength', 3, 15, 0.0, 45, 90, 3, 12, 0.0, 60, 120, 4, 10, 0.0, 75, 150, NULL),
(46, NULL, 'Dead Bug', 'Dead Bug : exercice de gainage anti-extension qui apprend à garder le bas du dos neutre pendant des mouvements de bras/jambes. Très pertinent pour les nageurs (coulées, ondulation, posture) car il améliore le contrôle lombo-pelvien avec très peu de charge. Priorité : qualité, respiration, amplitude maîtrisée.', 'https://fitnessprogramer.com/wp-content/uploads/2021/08/dead-bug.gif', 'strength', 3, 20, 0.0, 45, 90, 3, 16, 0.0, 60, 120, 4, 12, 0.0, 75, 150, NULL),
(47, NULL, 'Side Plank', 'Side Plank : gainage latéral (anti-flexion) renforçant obliques, quadratus lumborum et stabilité bassin. Très utile pour la transmission de force et la prévention des compensations (dos/hanche), notamment en crawl/dos. Garder le corps aligné, hanches hautes, respiration calme.', 'https://burnfit.io/wp-content/uploads/2023/11/SIDE_PLANK.gif', 'strength', 3, 30, 0.0, 45, 90, 4, 20, 0.0, 60, 120, 5, 12, 0.0, 75, 150, NULL),
(48, NULL, 'Suitcase Carry', 'Suitcase Carry : carry unilatéral (charge d''un seul côté) excellent pour anti-flexion latérale et stabilité du tronc. Très utile pour corriger les asymétries et renforcer la transmission de force sans fatigue excessive. Marcher "droit", épaules basses, bassin stable, ne pas se pencher vers la charge.', 'https://gymvisual.com/img/p/5/4/2/0/4/54204.gif', 'strength', 4, 30, 55.0, 90, 180, 4, 25, 65.0, 120, 240, 5, 20, 75.0, 150, 300, NULL),
(49, NULL, 'Face Pull', 'Face Pull : tirage haut au câble/élastique renforçant arrière d''épaule, coiffe et muscles scapulaires. Indispensable chez les nageurs pour équilibrer la grande quantité de mouvements au-dessus de la tête et limiter les douleurs d''épaule. Tirer vers le visage avec coudes ouverts, omoplates en arrière et en bas.', 'https://burnfit.io/wp-content/uploads/2023/11/FACE_PULL.gif', 'strength', 2, 20, 0.0, 45, 90, 3, 15, 0.0, 60, 120, 3, 10, 0.0, 75, 150, NULL),
(50, NULL, 'External Rotation Shoulder (Cable/Band)', 'External Rotation Shoulder (Cable/Band) : rotation externe ciblant la coiffe des rotateurs, fondamentale pour stabiliser l''épaule et réduire les risques de conflit/irritation chez les nageurs. Exercice "préhab" à faible coût fatigue : priorité à la qualité, amplitude contrôlée, omoplate stable (pas d''épaule qui remonte).', 'https://burnfit.io/wp-content/uploads/2023/11/CABLE_EXT_ROT.gif', 'strength', 2, 20, 0.0, 45, 90, 3, 15, 0.0, 60, 120, 3, 10, 0.0, 75, 150, NULL),
(51, NULL, 'Serratus Wall Slide', 'Serratus Wall Slide : exercice de contrôle scapulaire renforçant le serratus anterior (dentelé), clé pour une bonne élévation de bras et une épaule saine. Très utile pour améliorer la stabilité en streamline et sur les entrées de bras. Glisser les avant-bras au mur en gardant côtes basses, omoplates qui "tournent" sans compenser.', 'https://gymvisual.com/img/p/2/1/8/9/2/21892.gif', 'strength', 2, 20, 0.0, 45, 90, 3, 15, 0.0, 60, 120, 3, 10, 0.0, 75, 150, NULL),
(52, NULL, 'Scap Push-Up Plus', 'Scap Push-Up Plus : pompe scapulaire (sans flexion importante des coudes) visant le serratus et la stabilité de l''omoplate. Excellent pour la prévention d''épaule et le contrôle scapulaire en crawl/papillon. Garder le tronc gainé, pousser le sol pour "arrondir" légèrement le haut du dos, sans laisser les épaules monter aux oreilles.', 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Push-Up-Plus.gif', 'strength', 2, 20, 0.0, 45, 90, 3, 15, 0.0, 60, 120, 3, 10, 0.0, 75, 150, NULL),
(53, NULL, 'Rotational Med Ball Throw', 'Rotational Med Ball Throw : lancer rotationnel contre mur développant puissance du tronc et transfert hanches→épaules. Très utile pour la capacité à créer et transmettre de la force rapidement (virages, 4N, sprint), avec peu de charge articulaire. Intention explosive, mouvement "propre", récup suffisante entre reps.', NULL, 'strength', 4, 8, 0.0, 90, 240, 5, 6, 0.0, 120, 240, 6, 4, 0.0, 150, 300, NULL),
(54, NULL, 'Med Ball Side Toss', 'Med Ball Side Toss : lancer latéral puissant qui renforce la chaîne oblique et la coordination bassin-tronc-bras. Bon transfert sur la transmission de force et le contrôle rotationnel (virages, départs, stabilité en ondulation). Priorité : explosivité, pieds stables, ne pas "tordre" le bas du dos.', NULL, 'strength', 4, 8, 0.0, 90, 240, 5, 6, 0.0, 120, 240, 6, 4, 0.0, 150, 300, NULL),
(55, NULL, 'Med Ball Shot Put', 'Med Ball Shot Put : lancer type "poids" (unilatéral) développant puissance du haut du corps et transfert du sol vers la main via le tronc. Très utile en sprint pour améliorer la vitesse de production de force, tout en variant les angles de poussée. Garder les côtes basses, pousser fort, réception contrôlée.', NULL, 'strength', 4, 8, 0.0, 90, 240, 5, 6, 0.0, 120, 240, 6, 4, 0.0, 150, 300, NULL),
(56, NULL, 'Drop Jump to Stick', 'Drop Jump to Stick : saut depuis une hauteur avec réception "bloquée" (stick) pour apprendre à absorber la force et stabiliser les appuis. Très utile pour virages (freinage + réaccélération) et prévention, en travaillant l''alignement cheville-genou-hanche. Faible volume, qualité maximale, atterrissage silencieux.', NULL, 'strength', 4, 3, 0.0, 150, 300, 5, 3, 0.0, 180, 300, 6, 2, 0.0, 210, 360, NULL),
(57, NULL, 'Isometric Split Squat Hold', 'Isometric Split Squat Hold : maintien isométrique en position de fente pour renforcer stabilité hanche/genou et "stiffness" en angles spécifiques. Très utile pour consolider les appuis (virages/départs) et réduire les douleurs, avec une fatigue systémique faible. Tenir fort, tronc gainé, genou stable, respiration contrôlée.', NULL, 'strength', 3, 30, 0.0, 90, 240, 4, 20, 0.0, 120, 240, 5, 12, 0.0, 150, 300, NULL),
(58, NULL, 'Copenhagen Plank', 'Copenhagen Plank : gainage latéral ciblant fortement les adducteurs et la stabilité du bassin. Exercice très pertinent pour brasseurs et 4N, mais utile à tous pour robustesse hanche et prévention. Progression graduelle (levier court → long), garder le bassin haut et aligné.', NULL, 'strength', 3, 20, 0.0, 60, 120, 4, 15, 0.0, 75, 150, 5, 10, 0.0, 90, 180, NULL),
(59, NULL, 'Hip Airplane', 'Hip Airplane : exercice de contrôle moteur de hanche (rotation interne/externe) en appui unipodal, excellent pour la stabilité pelvienne et la prévention. Très utile pour améliorer la qualité des appuis et limiter les compensations (genou qui rentre, bassin qui tourne). Mouvement lent, amplitude maîtrisée, priorité à l''équilibre.', NULL, 'strength', 2, 8, 0.0, 60, 120, 3, 6, 0.0, 75, 150, 4, 5, 0.0, 90, 180, NULL)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. Import dim_seance (10 rows)
-- ---------------------------------------------------------------------------
INSERT INTO dim_seance (id, numero_seance, nom_seance, description) VALUES
(1,  'S1',  'Objectif : base force (tout nageur)',           'Séance socle : force utile + posture. Idéale toute l''année pour progresser sans casser la fraîcheur.'),
(2,  'S2',  'Objectif : jambes puissantes (murs)',           'Séance socle : jambes/chaîne postérieure pour mieux pousser au mur (départs/virages).'),
(3,  'S3',  'Objectif : départs (explosivité)',              'Séance bonus : explosivité et réactivité pour améliorer le départ.'),
(4,  'S4',  'Objectif : virages (appuis & relance)',         'Séance bonus : stabilité, freinage et relance pour gagner au virage.'),
(5,  'S5',  'Objectif : coulées (ligne & gainage)',          'Séance bonus : rigidité de ligne et contrôle bassin pour améliorer les coulées/ondulation.'),
(6,  'S6',  'Objectif : propulsion bras (sprint)',           'Séance bonus : tirage puissant et rapide pour améliorer la propulsion, surtout sprint.'),
(7,  'S7',  'Objectif : prévention épaules',                'Séance bonus : prévention/renforcement coiffe + scapula pour épaules solides en période de volume.'),
(8,  'S8',  'Objectif : stabilité hanche/genou (unilat)',    'Séance bonus : unilatéral et contrôle hanche/genou pour limiter les asymétries et améliorer les appuis.'),
(9,  'S9',  'Objectif : cardio muscu (condition)',           'Séance bonus : conditionnement général contrôlé, à utiliser en période légère ou intersaison.'),
(10, 'S10', 'Objectif : gainage (tronc)',                    'Séance bonus courte : gainage anti-rotation/anti-extension pour une meilleure transmission de force.')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. Import dim_seance_deroule (40 rows)
-- ---------------------------------------------------------------------------
INSERT INTO dim_seance_deroule (id, numero_seance, ordre, numero_exercice) VALUES
(80,  'S1',  1, 7),
(81,  'S1',  2, 4),
(82,  'S1',  3, 5),
(83,  'S1',  4, 45),
(84,  'S2',  1, 26),
(85,  'S2',  2, 3),
(86,  'S2',  3, 16),
(87,  'S2',  4, 46),
(88,  'S3',  1, 21),
(89,  'S3',  2, 20),
(90,  'S3',  3, 43),
(91,  'S3',  4, 44),
(92,  'S4',  1, 56),
(93,  'S4',  2, 33),
(94,  'S4',  3, 48),
(95,  'S4',  4, 45),
(96,  'S5',  1, 22),
(97,  'S5',  2, 36),
(98,  'S5',  3, 15),
(99,  'S5',  4, 51),
(100, 'S6',  1, 17),
(101, 'S6',  2, 13),
(102, 'S6',  3, 12),
(103, 'S6',  4, 49),
(104, 'S7',  1, 24),
(105, 'S7',  2, 49),
(106, 'S7',  3, 51),
(107, 'S7',  4, 50),
(108, 'S8',  1, 35),
(109, 'S8',  2, 37),
(110, 'S8',  3, 39),
(111, 'S8',  4, 58),
(112, 'S9',  1, 10),
(113, 'S9',  2, 30),
(114, 'S9',  3, 9),
(115, 'S9',  4, 31),
(116, 'S10', 1, 45),
(117, 'S10', 2, 46),
(118, 'S10', 3, 47),
(119, 'S10', 4, 48)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 5. Reset all SERIAL sequences
-- ---------------------------------------------------------------------------
SELECT setval('dim_exercices_id_seq', (SELECT COALESCE(MAX(id), 0) FROM dim_exercices));
SELECT setval('dim_seance_id_seq', (SELECT COALESCE(MAX(id), 0) FROM dim_seance));
SELECT setval('dim_seance_deroule_id_seq', (SELECT COALESCE(MAX(id), 0) FROM dim_seance_deroule));
